aws_access_key_id: ASIAZ65YCHZT54VQTI66
aws_secret_access_key: GuJRTYOU+DyfU84NlvxTHQi4jj8U97T8+a1A9O/d
aws_session_token: FwoGZXIvYXdzEAUaDMDYgGxWNJH8TTCVMCK/AYXAnItb43HfJN0XA8Sjx/mEL1ul67WqwC//molciwUwwfoBrwGClyyBBPgD2SNKzEW0iAW3LfVSXeTV6sCj7UFlvPBOLWTkAArwHmL4Y1we93aQkmGTw1DyZ/SQIStNRswT/dhixgyg0uj/Wakjn/ePCF2a2k5jfymG+W0h6FyXV2mx+pvZG8ewCOM0xrO2hJSnGx4uCthpR6KVBUm5VVPsW/9alCSITfuW+5KA4w0nSEMbLyKls/hE8jtPeSZ+KO2ez/MFMi3H+6psJuM4KvdbLPvfvB0HByVeZ0qxKJZZlMp1eWPhtfAPBjm9Rghz2wwaO+0=
region_name: us-east-1

